(() => {
  'use strict';
  const data = window.GTA_ROAD_MAP;
  const canvas = document.getElementById('roadMapCanvas');
  const stage = document.getElementById('atlas');
  if (!data || !canvas || !stage) return;

  const shell = document.getElementById('roadMapShell');
  const sidebar = shell.querySelector('.road-map-sidebar');
  const inspector = shell.querySelector('.road-inspector');
  const ctx = canvas.getContext('2d', { alpha: false, desynchronized: true });
  const WORLD = { minX: -4500, maxX: 4500, minY: -4000, maxY: 8500 };
  const DPR_LIMIT = 1.5;
  const $ = selector => document.querySelector(selector);
  const $$ = selector => [...document.querySelectorAll(selector)];

  sidebar.innerHTML = `<div class="road-map-brand"><span class="eyebrow">LIVE SERVER</span><h2>Alpár Atlas</h2><p>Valós idejű játékos-, jármű- és blipkövetés a kirajzolt GTA V úthálózaton.</p></div><div class="road-layer-group live-layer-group"><span class="road-tool-title">Élő rétegek</span><label><input type="checkbox" data-map-layer="players" checked><i></i>Játékosok <b id="layerPlayerCount">0</b></label><label><input type="checkbox" data-map-layer="vehicles" checked><i></i>Járművek <b id="layerVehicleCount">0</b></label><label><input type="checkbox" data-map-layer="blips" checked><i></i>Szerver blipek <b id="layerBlipCount">0</b></label><label><input type="checkbox" data-map-layer="labels" checked><i></i>Feliratok</label><label><input type="checkbox" data-map-layer="minor" checked><i></i>Mellékutak</label><label><input type="checkbox" data-map-layer="major" checked><i></i>Főutak</label></div><div class="live-follow-control"><span class="road-tool-title">Követés</span><button id="roadFollowActive" type="button">Kijelölt követése</button></div><div class="road-map-links"><a class="btn btn-outline" href="map.html">3D városmodell</a><button class="btn btn-dark" data-route="home">Vissza</button></div>`;
  inspector.classList.add('live-inspector');
  inspector.innerHTML = `<div class="road-inspector-head"><span class="eyebrow">SERVER TELEMETRY</span><h3>Élő egységek</h3></div><div class="road-summary live-summary"><div><b id="roadPlayerCount">0</b><span>játékos</span></div><div><b id="roadVehicleCount">0</b><span>jármű</span></div><div><b id="roadBlipCount">0</b><span>blip</span></div></div><div class="road-plan-status" id="roadPlanStatus"><i></i><span>Nincs szerveradat</span><b id="roadLastUpdate">SOHA</b></div><div class="live-entity-tabs"><button class="active" data-entity-filter="all">Mind</button><button data-entity-filter="player">Játékos</button><button data-entity-filter="vehicle">Jármű</button><button data-entity-filter="blip">Blip</button></div><div class="road-selection-list live-entity-list" id="roadSelectionList"><div class="road-empty"><i>⌁</i><b>Kapcsolatra vár</b><p>A FiveM szerver első adatcsomagja után automatikusan feltöltődik.</p></div></div><div class="live-feed-note"><b>Automatikus frissítés</b><span>A mozgást interpoláció simítja, ezért az ikonok nem ugrálnak.</span></div><div class="road-legend"><span><i class="live-player"></i>Játékos</span><span><i class="live-vehicle"></i>Jármű</span><span><i class="live-blip"></i>Blip</span><span><i class="major"></i>Főút</span></div>`;
  $('.road-map-topbar').innerHTML = `<label class="road-map-search"><span>⌕</span><input id="roadMapSearch" type="search" placeholder="Játékos, rendszám, blip vagy koordináta…"><button type="button" id="roadMapSearchButton">Keresés</button></label><a class="road-map-3d-launch" href="map.html"><b>3D</b><span>ATLAS</span></a><div class="road-map-actions"><button id="roadMapReset" type="button" title="Teljes térkép" aria-label="Teljes térkép">⌂</button><button id="roadMapFullscreen" type="button" title="Teljes képernyő" aria-label="Teljes képernyő">⛶</button></div>`;
  stage.dataset.tool = 'pan';
  stage.setAttribute('aria-label', 'Alpár RP élő szervertérkép');
  $('.road-map-hint').innerHTML = '<b>Élő térkép</b><span>Húzd a térképet, nagyíts, majd kattints egy entitásra.</span>';
  stage.insertAdjacentHTML('beforeend', '<div class="road-live-badge is-waiting" id="roadLiveBadge"><i></i><span>KAPCSOLATRA VÁR</span><b id="roadLiveLatency">--</b></div>');

  const makeLayer = () => { const layer = document.createElement('canvas'); layer.width = layer.height = data.size; return layer; };
  const baseCache = makeLayer(), minorCache = makeLayer(), majorCache = makeLayer();
  const baseCtx = baseCache.getContext('2d'), minorCtx = minorCache.getContext('2d'), majorCtx = majorCache.getContext('2d');
  const state = { zoom: .84, panX: 0, panY: 0, dpr: 1, dragging: false, dragX: 0, dragY: 0, moved: false, pointers: new Map(), pinchDistance: 0, pinchCenter: null, entities: new Map(), selected: null, follow: false, filter: 'all', connected: false, lastUpdate: 0, lastListSignature: '', layers: { players: true, vehicles: true, blips: true, labels: true, minor: true, major: true }, raf: 0 };

  function path(target, points, closed = false) { if (!points?.length) return; target.beginPath(); target.moveTo(...points[0]); for (let i = 1; i < points.length; i += 1) target.lineTo(...points[i]); if (closed) target.closePath(); }
  function roadStyle(road) { return road.c === 2 ? ['#3a0a12','#d5263e',6.2,3.35] : road.c === 1 ? ['#151c23','#697784',3.7,1.9] : ['#10151a','#394550',2.25,1.05]; }
  function strokeRoad(target, road) { const s = roadStyle(road); target.lineCap='round'; target.lineJoin='round'; target.strokeStyle=s[0]; target.lineWidth=s[2]; path(target,road.p); target.stroke(); target.strokeStyle=s[1]; target.lineWidth=s[3]; path(target,road.p); target.stroke(); }
  function buildCache() { baseCtx.fillStyle='#090c10'; path(baseCtx,data.coast,true); baseCtx.fill(); (data.water||[]).forEach(w=>{baseCtx.fillStyle='#04070a';path(baseCtx,w,true);baseCtx.fill();}); data.roads.forEach(road=>strokeRoad(road.c===0?minorCtx:majorCtx,road)); }
  function fitScale() { return Math.min(canvas.width/state.dpr,canvas.height/state.dpr)/data.size; }
  function view() { const width=canvas.width/state.dpr,height=canvas.height/state.dpr,scale=fitScale()*state.zoom; return {width,height,scale,x:width/2-data.size*scale/2+state.panX,y:height/2-data.size*scale/2+state.panY}; }
  function worldToMap(p) { return {x:(Number(p.x)-WORLD.minX)/(WORLD.maxX-WORLD.minX)*data.size,y:(WORLD.maxY-Number(p.y))/(WORLD.maxY-WORLD.minY)*data.size}; }
  function mapToWorld(p) { return {x:WORLD.minX+p.x/data.size*(WORLD.maxX-WORLD.minX),y:WORLD.maxY-p.y/data.size*(WORLD.maxY-WORLD.minY)}; }
  function screenToMap(x,y) { const rect=canvas.getBoundingClientRect(),v=view(); return {x:(x-rect.left-v.x)/v.scale,y:(y-rect.top-v.y)/v.scale}; }
  const entityKey = entity => `${entity.type}:${entity.id}`;
  const escapeHTML = value => String(value??'').replace(/[&<>"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[char]));
  function normalize(raw,type,index=0) { const source=raw&&typeof raw==='object'?raw:{},id=String(source.id??source.serverId??source.netId??`${type}-${index}`),point=worldToMap(source.coords||source.position||source); return {...source,type,id,x:Number.isFinite(point.x)?point.x:0,y:Number.isFinite(point.y)?point.y:0,targetX:Number.isFinite(point.x)?point.x:0,targetY:Number.isFinite(point.y)?point.y:0,label:String(source.name||source.label||source.plate||`${type} ${id}`).slice(0,80),heading:Number.isFinite(Number(source.heading))?Number(source.heading):0,color:/^#[0-9a-f]{6}$/i.test(source.color||'')?source.color:undefined}; }
  function applyFeed(payload={}) { const seen=new Set(),incoming=[...(Array.isArray(payload.players)?payload.players:[]).map((e,i)=>normalize(e,'player',i)),...(Array.isArray(payload.vehicles)?payload.vehicles:[]).map((e,i)=>normalize(e,'vehicle',i)),...(Array.isArray(payload.blips)?payload.blips:[]).map((e,i)=>normalize(e,'blip',i))]; incoming.forEach(entity=>{const key=entityKey(entity),old=state.entities.get(key);seen.add(key);state.entities.set(key,old?{...old,...entity,x:old.x,y:old.y,targetX:entity.x,targetY:entity.y}:entity);}); [...state.entities.keys()].forEach(key=>{if(!seen.has(key))state.entities.delete(key);}); state.connected=Boolean(payload.updatedAt); const parsed=Date.parse(payload.updatedAt||''); state.lastUpdate=Number.isFinite(parsed)?parsed:0; updateUI(); invalidate(); }
  function colorFor(entity) { return entity.color||(entity.type==='player'?'#35e889':entity.type==='vehicle'?'#49a6ff':'#ffb02e'); }
  function drawEntity(entity,v) { const x=v.x+entity.x*v.scale,y=v.y+entity.y*v.scale,color=colorFor(entity),selected=state.selected===entityKey(entity); ctx.save();ctx.translate(x,y);ctx.rotate(entity.heading*Math.PI/180);ctx.shadowColor=color;ctx.shadowBlur=selected?22:10;ctx.fillStyle=color;ctx.strokeStyle='#fff';ctx.lineWidth=selected?2.5:1.4;if(entity.type==='vehicle'){ctx.beginPath();ctx.roundRect(-6,-10,12,20,3);ctx.fill();ctx.stroke();}else if(entity.type==='blip'){ctx.beginPath();ctx.moveTo(0,-10);ctx.lineTo(8,6);ctx.lineTo(0,10);ctx.lineTo(-8,6);ctx.closePath();ctx.fill();ctx.stroke();}else{ctx.beginPath();ctx.arc(0,0,selected?8:6,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.beginPath();ctx.moveTo(0,-13);ctx.lineTo(4,-7);ctx.lineTo(-4,-7);ctx.closePath();ctx.fill();}ctx.restore();if(state.layers.labels&&(selected||state.zoom>1.15)){ctx.font='800 9px Inter,sans-serif';const width=ctx.measureText(entity.label).width+14;ctx.fillStyle='rgba(3,6,9,.88)';ctx.fillRect(x+11,y-10,width,20);ctx.fillStyle='#eef5fa';ctx.fillText(entity.label,x+18,y+3);} }
  function render() { state.raf=0;const v=view();ctx.setTransform(state.dpr,0,0,state.dpr,0,0);const gradient=ctx.createRadialGradient(v.width/2,v.height/2,0,v.width/2,v.height/2,Math.max(v.width,v.height));gradient.addColorStop(0,'#111820');gradient.addColorStop(1,'#030507');ctx.fillStyle=gradient;ctx.fillRect(0,0,v.width,v.height);ctx.save();ctx.translate(v.x,v.y);ctx.scale(v.scale,v.scale);ctx.drawImage(baseCache,0,0);if(state.layers.minor)ctx.drawImage(minorCache,0,0);if(state.layers.major)ctx.drawImage(majorCache,0,0);ctx.restore();let moving=false;state.entities.forEach(entity=>{entity.x+=(entity.targetX-entity.x)*.22;entity.y+=(entity.targetY-entity.y)*.22;if(Math.abs(entity.targetX-entity.x)+Math.abs(entity.targetY-entity.y)>.02)moving=true;if(state.layers[`${entity.type}s`])drawEntity(entity,v);});if(state.follow&&state.selected){const entity=state.entities.get(state.selected);if(entity){const dx=v.width/2-(v.x+entity.x*v.scale),dy=v.height/2-(v.y+entity.y*v.scale);if(Math.abs(dx)+Math.abs(dy)>.25){state.panX+=dx;state.panY+=dy;moving=true;}}}if(moving)invalidate(); }
  function invalidate() { if(!state.raf)state.raf=requestAnimationFrame(render); }
  function resize() { const rect=stage.getBoundingClientRect();if(rect.width<2||rect.height<2)return;state.dpr=Math.min(devicePixelRatio||1,DPR_LIMIT);canvas.width=Math.round(rect.width*state.dpr);canvas.height=Math.round(rect.height*state.dpr);canvas.style.width=`${rect.width}px`;canvas.style.height=`${rect.height}px`;invalidate(); }
  function updateUI() { const counts={player:0,vehicle:0,blip:0};state.entities.forEach(entity=>counts[entity.type]++);$('#roadPlayerCount').textContent=$('#layerPlayerCount').textContent=counts.player;$('#roadVehicleCount').textContent=$('#layerVehicleCount').textContent=counts.vehicle;$('#roadBlipCount').textContent=$('#layerBlipCount').textContent=counts.blip;const status=$('#roadPlanStatus'),badge=$('#roadLiveBadge');status.classList.toggle('is-dirty',!state.connected);status.querySelector('span').textContent=state.connected?'Élő adatfolyam':'Nincs szerveradat';badge.classList.toggle('is-waiting',!state.connected);badge.querySelector('span').textContent=state.connected?'LIVE':'KAPCSOLATRA VÁR';$('#roadLastUpdate').textContent=state.lastUpdate?new Date(state.lastUpdate).toLocaleTimeString('hu-HU'):'SOHA';renderList(); }
  function renderList() { const list=$('#roadSelectionList'),items=[...state.entities.values()].filter(entity=>state.filter==='all'||entity.type===state.filter),signature=`${state.filter}|${state.selected}|${items.map(entity=>`${entityKey(entity)}:${entity.label}:${entity.job||''}:${entity.plate||''}:${entity.model||''}`).join('|')}`;if(signature===state.lastListSignature)return;state.lastListSignature=signature;list.innerHTML=items.slice(0,250).map(entity=>{const key=entityKey(entity),meta=entity.type==='player'?`ID ${entity.serverId??entity.id} · ${entity.job||'játékos'}`:entity.type==='vehicle'?`${entity.plate||'NINCS RENDSZÁM'} · ${entity.model||'jármű'}`:`${entity.category||'szerver blip'} · ${Math.round(entity.x)}, ${Math.round(entity.y)}`;return `<article class="${state.selected===key?'is-selected':''}" data-entity-key="${escapeHTML(key)}"><i class="live-${entity.type}"></i><span><b>${escapeHTML(entity.label)}</b><small>${escapeHTML(meta)}</small></span><button aria-label="Középre">⌖</button></article>`;}).join('')||'<div class="road-empty"><i>⌁</i><b>Nincs megjeleníthető adat</b><p>A FiveM bridge még nem küldött entitásokat ebbe a kategóriába.</p></div>'; }
  function focus(entity,zoom=Math.max(state.zoom,2.1)) { state.zoom=zoom;const v=view();state.panX+=v.width/2-(v.x+entity.x*v.scale);state.panY+=v.height/2-(v.y+entity.y*v.scale);$('#roadZoom').textContent=`${Math.round(state.zoom*100)}%`;invalidate(); }
  function zoomAt(clientX,clientY,factor) { const rect=canvas.getBoundingClientRect(),point=screenToMap(clientX,clientY);state.zoom=Math.max(.58,Math.min(7,state.zoom*factor));const v=view();state.panX+=clientX-rect.left-(v.x+point.x*v.scale);state.panY+=clientY-rect.top-(v.y+point.y*v.scale);$('#roadZoom').textContent=`${Math.round(state.zoom*100)}%`;invalidate(); }
  function pick(clientX,clientY) { const point=screenToMap(clientX,clientY),limit=18/(fitScale()*state.zoom);let best=null,distance=limit;state.entities.forEach(entity=>{if(!state.layers[`${entity.type}s`])return;const next=Math.hypot(entity.x-point.x,entity.y-point.y);if(next<distance){best=entity;distance=next;}});if(best){state.selected=entityKey(best);state.lastListSignature='';focus(best);renderList();} }

  canvas.addEventListener('wheel',event=>{event.preventDefault();zoomAt(event.clientX,event.clientY,event.deltaY<0?1.13:.885);},{passive:false});
  canvas.addEventListener('pointerdown',event=>{state.pointers.set(event.pointerId,{x:event.clientX,y:event.clientY});if(state.pointers.size===2){const p=[...state.pointers.values()];state.pinchDistance=Math.hypot(p[1].x-p[0].x,p[1].y-p[0].y);state.pinchCenter={x:(p[0].x+p[1].x)/2,y:(p[0].y+p[1].y)/2};state.moved=true;return;}state.dragging=true;state.moved=false;state.dragX=event.clientX-state.panX;state.dragY=event.clientY-state.panY;canvas.setPointerCapture(event.pointerId);canvas.classList.add('dragging');});
  canvas.addEventListener('pointermove',event=>{if(state.pointers.has(event.pointerId))state.pointers.set(event.pointerId,{x:event.clientX,y:event.clientY});if(state.pointers.size===2){const p=[...state.pointers.values()],distance=Math.hypot(p[1].x-p[0].x,p[1].y-p[0].y),center={x:(p[0].x+p[1].x)/2,y:(p[0].y+p[1].y)/2};if(state.pinchDistance>0)zoomAt(center.x,center.y,distance/state.pinchDistance);if(state.pinchCenter){state.panX+=center.x-state.pinchCenter.x;state.panY+=center.y-state.pinchCenter.y;}state.pinchDistance=distance;state.pinchCenter=center;invalidate();return;}const point=screenToMap(event.clientX,event.clientY),world=mapToWorld(point);$('#roadCoordX').textContent=Math.round(world.x);$('#roadCoordY').textContent=Math.round(world.y);if(state.dragging){if(Math.abs(event.clientX-state.dragX-state.panX)+Math.abs(event.clientY-state.dragY-state.panY)>2)state.moved=true;state.follow=false;state.panX=event.clientX-state.dragX;state.panY=event.clientY-state.dragY;invalidate();}});
  function endPointer(event) { state.pointers.delete(event.pointerId);if(state.pointers.size<2){state.pinchDistance=0;state.pinchCenter=null;}if(event.type==='pointerup'&&!state.moved)pick(event.clientX,event.clientY);state.dragging=false;canvas.classList.remove('dragging'); }
  canvas.addEventListener('pointerup',endPointer);canvas.addEventListener('pointercancel',endPointer);
  $$('[data-map-layer]').forEach(input=>input.addEventListener('change',()=>{state.layers[input.dataset.mapLayer]=input.checked;invalidate();}));
  $$('[data-entity-filter]').forEach(button=>button.addEventListener('click',()=>{$$('[data-entity-filter]').forEach(item=>item.classList.remove('active'));button.classList.add('active');state.filter=button.dataset.entityFilter;state.lastListSignature='';renderList();}));
  $('#roadSelectionList').addEventListener('click',event=>{const row=event.target.closest('[data-entity-key]');if(!row)return;state.selected=row.dataset.entityKey;state.lastListSignature='';const entity=state.entities.get(state.selected);if(entity)focus(entity);renderList();});
  $('#roadFollowActive').addEventListener('click',()=>{state.follow=!state.follow;$('#roadFollowActive').classList.toggle('active',state.follow);invalidate();});
  $('#roadMapReset').addEventListener('click',()=>{state.zoom=.84;state.panX=state.panY=0;state.follow=false;$('#roadFollowActive').classList.remove('active');$('#roadZoom').textContent='84%';invalidate();});
  $('#roadMapFullscreen').addEventListener('click',async()=>{try{if(!document.fullscreenElement)await shell.requestFullscreen();else await document.exitFullscreen();}catch(_){}});
  $('#roadZoomIn').addEventListener('click',()=>{const rect=canvas.getBoundingClientRect();zoomAt(rect.left+rect.width/2,rect.top+rect.height/2,1.18);});
  $('#roadZoomOut').addEventListener('click',()=>{const rect=canvas.getBoundingClientRect();zoomAt(rect.left+rect.width/2,rect.top+rect.height/2,.84);});
  function search() { const query=$('#roadMapSearch').value.trim().toLowerCase();if(!query)return;const match=[...state.entities.values()].find(entity=>`${entity.label} ${entity.plate||''} ${entity.id}`.toLowerCase().includes(query)),coords=query.match(/(-?\d+(?:\.\d+)?)\s*[,;/ ]\s*(-?\d+(?:\.\d+)?)/);if(match){state.selected=entityKey(match);state.lastListSignature='';focus(match);renderList();}else if(coords)focus(normalize({id:'search',x:+coords[1],y:+coords[2]},'blip'));else window.dispatchEvent(new CustomEvent('alpar:toast',{detail:'Nincs ilyen élő entitás vagy koordináta.'})); }
  $('#roadMapSearchButton').addEventListener('click',search);$('#roadMapSearch').addEventListener('keydown',event=>{if(event.key==='Enter')search();});
  let events;
  function connect() { if(events)return;events=new EventSource('/api/live-map/events');events.addEventListener('map',event=>{try{applyFeed(JSON.parse(event.data));}catch(_){}});events.onerror=()=>{state.connected=false;updateUI();}; }
  setInterval(()=>{const age=Math.max(0,Date.now()-state.lastUpdate);if(state.connected&&age>15000){state.connected=false;updateUI();}$('#roadLiveLatency').textContent=state.connected?`${Math.round(age/100)/10} s`:'--';},1000);
  window.addEventListener('resize',resize,{passive:true});new ResizeObserver(resize).observe(stage);window.addEventListener('alpar:map-visible',resize);window.addEventListener('pagehide',()=>events?.close(),{once:true});
  buildCache();resize();updateUI();connect();
  window.AlparRoadMap={resize,applyFeed,getState:()=>({entities:[...state.entities.values()],connected:state.connected})};
})();
